# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Use a package of configuration called an orb.
orbs:
  node: circleci/node@4.2.0
  aws-cli: circleci/aws-cli@1.4.1
jobs:
  run_tests:
    docker:
      - image: circleci/node:10
    steps:  
      - checkout
      - run:
          name: Install npm dependencies
          command: |
            npm install --save
      - run:
          name: Run unit tests
          command: |
            npm run test
      - save_cache:
          name: Saving Cache
          key: node-v1-{{ .Branch }}-{{ checksum "package-lock.json" }}
  run_build:
    docker:
      - image: circleci/node:10
    steps:  
      - checkout
      - run:
          name: Install npm dependencies
          command: |
            npm install --save   
      - run:
          name: Build
          command: |
            npm run build
  run_deploy:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run:
          name: Deploy
          command: |
            npm run cdk:deploy:rest-api-proxy
workflows:
  test:
    jobs:
      - run_tests
      - run_build:
          requires:
            - run_tests
      - run_deploy:
          requires:
            - run_build
